import React, { useContext, useEffect, useState } from 'react';
import { Download, CheckCircle } from 'lucide-react';
import MainLayout from '../components/MainLayout';
import ProgressBar from '../components/ProgressBar';
import { ChecklistContext } from '../context/ChecklistContext';
import BallotBox from '../illustrations/BallotBox';
import VoterFinger from '../illustrations/VoterFinger';
import TranslateText from '../components/TranslateText';

const CHECKLIST_ITEMS = {
  before: [
    { id: 'b1', title: 'Check Voter Registration', desc: 'Verify your name is on the Electoral Roll at voters.eci.gov.in using your EPIC card or Aadhaar.' },
    { id: 'b2', title: 'Find Your Polling Booth', desc: 'Look up your designated polling booth address and timing on the ECI portal.' },
    { id: 'b3', title: 'Verify Your ID Documents', desc: 'Confirm you have at least one valid photo ID (EPIC card, Aadhaar, PAN, Passport, etc.).' },
    { id: 'b4', title: 'Note Down Booth Timings', desc: 'Polling usually runs from 7 AM to 6 PM. Check your state\'s specific schedule.' },
  ],
  onday: [
    { id: 'd1', title: 'Carry Your Valid Photo ID', desc: 'Bring any one of the 12 approved photo identity documents to the polling booth.' },
    { id: 'd2', title: 'Join the Queue Patiently', desc: 'Arrive early to avoid rush. Queues can be long — your place is protected if you are in line before closing.' },
    { id: 'd3', title: 'Show Your ID & Get Inked', desc: 'Present your ID to booth officials. Your index finger will be marked with indelible ink.' },
    { id: 'd4', title: 'Use the EVM & Cast Your Vote', desc: 'Press the button next to your chosen candidate. A beep confirms your vote. Your vote is 100% secret.' },
  ],
};

const TOTAL = 8;

const ChecklistItem = ({ item, isChecked, onToggle }) => (
  <div
    className={`flex items-start gap-4 p-4 md:p-5 rounded-card border transition-all duration-300 ${
      isChecked ? 'bg-forest-light border-forest' : 'bg-white border-gray-200 hover:border-saffron'
    }`}
  >
    <button
      role="checkbox"
      aria-checked={isChecked}
      onClick={() => onToggle(item.id)}
      className={`flex-shrink-0 w-7 h-7 rounded-full border-2 flex items-center justify-center transition-all duration-200 focus:ring-2 focus:ring-saffron focus:outline-none mt-0.5 ${
        isChecked ? 'bg-forest border-forest animate-check-in' : 'border-gray-400 bg-white hover:border-saffron'
      }`}
      aria-label={`${isChecked ? 'Uncheck' : 'Check'} step: ${item.title}`}
    >
      {isChecked && <CheckCircle size={16} className="text-white" />}
    </button>
    <div className="flex-1 min-w-0">
      <h3 className={`text-small md:text-base font-semibold mb-1 ${isChecked ? 'text-forest line-through decoration-forest/60' : 'text-navy'}`}>
        <TranslateText>{item.title}</TranslateText>
      </h3>
      <p className={`text-small mb-0 ${isChecked ? 'text-forest/80' : 'text-[#5C5C5C]'}`}><TranslateText>{item.desc}</TranslateText></p>
    </div>
  </div>
);

const VoterChecklist = () => {
  const { checkedItems, toggleItem, completedCount } = useContext(ChecklistContext);
  const [downloaded, setDownloaded] = useState(false);
  const progressPercent = (completedCount / TOTAL) * 100;
  const allDone = completedCount === TOTAL;
  const downloadEnabled = completedCount >= 4;

  const handleDownload = () => {
    const checkedTitles = [
      ...CHECKLIST_ITEMS.before.filter(i => checkedItems[i.id]),
      ...CHECKLIST_ITEMS.onday.filter(i => checkedItems[i.id]),
    ].map(i => `✅ ${i.title}`).join('\n');

    const content = `My VoterPath India Plan\n${'='.repeat(30)}\n\nDate: ${new Date().toLocaleDateString('en-IN')}\n\nCompleted Steps:\n${checkedTitles}\n\nSource: voters.eci.gov.in\nGenerated by VoterPath India`;

    try {
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'MyVoterPlan.txt';
      a.click();
      URL.revokeObjectURL(url);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 2000);
    } catch {
      alert('Download unavailable in this browser.');
    }
  };

  return (
    <MainLayout>
      <div className="page-container section-spacing">
        {/* Header */}
        <div className="flex items-start justify-between gap-6 mb-8">
          <div className="flex-1">
            <h1 className="text-h1 text-navy font-bold mb-2"><TranslateText>Voter Checklist</TranslateText></h1>
            <p className="text-small text-[#5C5C5C] mb-4"><TranslateText>Complete these steps to vote with full confidence.</TranslateText></p>
            {/* Progress */}
            <div className="flex items-center gap-3 mb-2">
              <span className="text-small font-semibold text-navy">{completedCount} <TranslateText>of</TranslateText> {TOTAL} <TranslateText>steps complete</TranslateText></span>
              {allDone && <span className="text-meta font-bold text-forest"><TranslateText>🎉 All done!</TranslateText></span>}
            </div>
            <ProgressBar progress={progressPercent} className="max-w-sm" />
            {completedCount < 4 && (
              <p className="text-meta text-[#5C5C5C] mt-2"><TranslateText>Complete at least 4 steps to download your plan.</TranslateText></p>
            )}
          </div>
          <div className="hidden md:block flex-shrink-0" aria-hidden="true">
            <BallotBox className="w-28 h-32" />
          </div>
        </div>

        {/* Personalized Roadmap Tool */}
        <div className="card mb-8 bg-blue-50 border border-blue-100">
          <h3 className="text-h3 text-navy font-semibold mb-2"><TranslateText>Personalize Your Roadmap</TranslateText></h3>
          <div className="flex flex-col md:flex-row gap-4">
            <select 
              className="input-field bg-white" 
              defaultValue=""
              onChange={(e) => {
                if (e.target.value === 'under18') {
                  alert("As a 17-year-old, you can now apply in advance to get enrolled when you turn 18! Look for Form 6 on the ECI portal.");
                }
              }}
            >
              <option value="" disabled>Select your age group</option>
              <option value="under18">Under 18 (Pre-Registration)</option>
              <option value="18plus">18 Years or Older (Voter)</option>
            </select>
            <select className="input-field bg-white" defaultValue="">
              <option value="" disabled>Select your state</option>
              <option value="mh">Maharashtra</option>
              <option value="dl">Delhi</option>
              <option value="ka">Karnataka</option>
              <option value="other">Other State</option>
            </select>
          </div>
        </div>

        {/* Section 1: Before Election Day */}
        <section aria-labelledby="before-heading" className="mb-8">
          <h2 id="before-heading" className="text-h2 text-navy font-semibold mb-4 flex items-center gap-2">
            <span className="w-8 h-8 bg-saffron text-white rounded-full flex items-center justify-center text-[14px] font-bold">1</span>
            <TranslateText>Before Election Day</TranslateText>
          </h2>
          <div className="flex flex-col gap-3">
            {CHECKLIST_ITEMS.before.map(item => (
              <ChecklistItem key={item.id} item={item} isChecked={!!checkedItems[item.id]} onToggle={toggleItem} />
            ))}
          </div>
        </section>

        {/* Section 2: On Election Day */}
        <section aria-labelledby="onday-heading" className="mb-8">
          <h2 id="onday-heading" className="text-h2 text-navy font-semibold mb-4 flex items-center gap-2">
            <span className="w-8 h-8 bg-saffron text-white rounded-full flex items-center justify-center text-[14px] font-bold">2</span>
            <TranslateText>On Election Day</TranslateText>
          </h2>
          <div className="flex flex-col gap-3">
            {CHECKLIST_ITEMS.onday.map(item => (
              <ChecklistItem key={item.id} item={item} isChecked={!!checkedItems[item.id]} onToggle={toggleItem} />
            ))}
          </div>
        </section>

        {/* Session note */}
        <p className="text-meta text-[#5C5C5C] text-center mb-6" role="note">
          <TranslateText>ℹ️ Your progress is saved for this session only.</TranslateText>
        </p>

        {/* Download Button */}
        <button
          onClick={handleDownload}
          disabled={!downloadEnabled}
          className={`w-full btn text-base py-4 gap-3 rounded-card transition-all ${
            downloadEnabled
              ? downloaded
                ? 'bg-forest text-white cursor-default'
                : 'bg-saffron text-white hover:bg-saffron-dark shadow-md hover:shadow-lg'
              : 'bg-gray-200 text-gray-400 cursor-not-allowed'
          }`}
          aria-disabled={!downloadEnabled}
          aria-label={downloadEnabled ? 'Download my voter plan as a text file' : 'Complete at least 4 steps to download your plan'}
        >
          <Download size={20} />
          {downloaded ? <TranslateText>Downloaded ✓</TranslateText> : <TranslateText>Download My Voter Plan</TranslateText>}
        </button>

        {/* Completion Celebration */}
        {allDone && (
          <div className="mt-8 flex flex-col items-center gap-4 animate-fade-in text-center py-6 bg-forest-light rounded-card border border-forest">
            <VoterFinger className="w-24 h-24" />
            <h2 className="text-h2 text-forest font-bold mb-0"><TranslateText>You're Ready to Vote!</TranslateText></h2>
            <p className="text-small text-forest/80 max-w-sm">
              <TranslateText>You've completed all 8 steps. Walk into your polling booth with confidence. Every vote counts. 🇮🇳</TranslateText>
            </p>
          </div>
        )}
      </div>
    </MainLayout>
  );
};

export default VoterChecklist;
